
GET http://localhost/conselho-server/dev/playground HTTP/1.1
Accept: application/json
Content-Type: application/json
Prettify: true

###

POST http://localhost/conselho-server/user HTTP/1.1
Content-Type: application/json
Accept: application/json
Prettify: true

{
    "name": "Ayrton Fidelis",
    "email": "ayrton.vargas33@gmail.com",
    "password": "senha"
}

###

POST http://localhost/conselho-server/user_token HTTP/1.1
Content-Type: application/json
Accept: application/json
Prettify: true

{
    "email": "ayrton.vargas33@gmail.com",
    "password": "senha"
}

###

GET http://localhost/conselho-server/user HTTP/1.1
Content-Type: application/json
Accept: application/json
Prettify: true
Token: 54851698fbea85a67ea7f731f758e4fd537302ca1343981aecf5dcafa83616e4

### 

http://localhost/conselho-server/dev/rebuild_schemas
Accept: application/json
Content-Type: application/json

### 

http://localhost/conselho-server/dev/populate_database
Accept: application/json
Content-Type: application/json

### 
