-- MySQL Script generated by MySQL Workbench
-- seg 14 mai 2018 21:50:54 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema conselho
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `email` VARCHAR(100) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `password` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subject` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `name` VARCHAR(50) NOT NULL,
  `school_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `school_id_idx` (`school_id` ASC),
  UNIQUE INDEX `subject_unique` (`school_id` ASC, `name` ASC),
  CONSTRAINT `subject-school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grade` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `level` INT UNSIGNED NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `school_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `school_id_idx` (`school_id` ASC),
  UNIQUE INDEX `grade_unique` (`school_id` ASC, `name` ASC),
  CONSTRAINT `grade-school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grade_subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grade_subject` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `grade_id` INT UNSIGNED NOT NULL,
  `subject_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `grade_id_idx` (`grade_id` ASC),
  INDEX `subject_id_idx` (`subject_id` ASC),
  UNIQUE INDEX `grade_subject_unique` (`grade_id` ASC, `subject_id` ASC),
  CONSTRAINT `grade_subject-grade_id`
    FOREIGN KEY (`grade_id`)
    REFERENCES `grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `grade_subject-subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `school_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `school_id_idx` (`school_id` ASC),
  CONSTRAINT `student-school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `topic_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `topic_option` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `name` VARCHAR(50) NOT NULL,
  `value` INT UNSIGNED NOT NULL,
  `topic_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `topic_option-topic_id_idx` (`topic_id` ASC),
  UNIQUE INDEX `topic_option_unique_name` (`topic_id` ASC, `name` ASC),
  UNIQUE INDEX `topic_option_unique_value` (`topic_id` ASC, `value` ASC),
  CONSTRAINT `topic_option-topic_id`
    FOREIGN KEY (`topic_id`)
    REFERENCES `topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `topic` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `name` VARCHAR(50) NOT NULL,
  `school_id` INT UNSIGNED NOT NULL,
  `topic_option_id` INT UNSIGNED NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `school_id_idx` (`school_id` ASC),
  UNIQUE INDEX `topic_unique` (`name` ASC, `school_id` ASC),
  INDEX `topic-topic_option_id_idx` (`topic_option_id` ASC),
  CONSTRAINT `topic-school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `topic-topic_option_id`
    FOREIGN KEY (`topic_option_id`)
    REFERENCES `topic_option` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `council`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `council` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `name` VARCHAR(50) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `school_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `school_id_idx` (`school_id` ASC),
  UNIQUE INDEX `council_unique` (`school_id` ASC, `name` ASC),
  CONSTRAINT `council-school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `council_id` INT UNSIGNED NOT NULL,
  `grade_id` INT UNSIGNED NOT NULL,
  `student_id` INT UNSIGNED NOT NULL,
  `subject_id` INT UNSIGNED NOT NULL,
  `topic_option_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `council_id_idx` (`council_id` ASC),
  INDEX `grade_id_idx` (`grade_id` ASC),
  INDEX `student_id_idx` (`student_id` ASC),
  INDEX `subject_id_idx` (`subject_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  UNIQUE INDEX `evaluation_unique` (`student_id` ASC, `user_id` ASC, `topic_option_id` ASC, `subject_id` ASC, `council_id` ASC),
  INDEX `evaluation-topic_option_id_idx` (`topic_option_id` ASC),
  CONSTRAINT `evaluation-council_id`
    FOREIGN KEY (`council_id`)
    REFERENCES `council` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `evaluation-grade_id`
    FOREIGN KEY (`grade_id`)
    REFERENCES `grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `evaluation-student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `evaluation-subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `evaluation-topic_option_id`
    FOREIGN KEY (`topic_option_id`)
    REFERENCES `topic_option` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `evaluation-user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grade_observation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grade_observation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(300) NOT NULL,
  `council_id` INT UNSIGNED NOT NULL,
  `grade_id` INT UNSIGNED NOT NULL,
  `subject_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `council_id_idx` (`council_id` ASC),
  INDEX `grade_id_idx` (`grade_id` ASC),
  INDEX `subject_id_idx` (`subject_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  UNIQUE INDEX `grade_observation_unique` (`grade_id` ASC, `council_id` ASC, `user_id` ASC, `subject_id` ASC),
  CONSTRAINT `grade_observation-council_id`
    FOREIGN KEY (`council_id`)
    REFERENCES `council` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `grade_observation-grade_id`
    FOREIGN KEY (`grade_id`)
    REFERENCES `grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `grade_observation-subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `grade_observation-user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_observation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_observation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(300) NOT NULL,
  `council_id` INT UNSIGNED NOT NULL,
  `grade_id` INT UNSIGNED NOT NULL,
  `student_id` INT UNSIGNED NOT NULL,
  `subject_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `council_id_idx` (`council_id` ASC),
  INDEX `grade_id_idx` (`grade_id` ASC),
  INDEX `student_id_idx` (`student_id` ASC),
  INDEX `subject_id_idx` (`subject_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  UNIQUE INDEX `student_observation_unique` (`student_id` ASC, `user_id` ASC, `subject_id` ASC, `council_id` ASC),
  CONSTRAINT `student_observation-council_id`
    FOREIGN KEY (`council_id`)
    REFERENCES `council` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_observation-grade_id`
    FOREIGN KEY (`grade_id`)
    REFERENCES `grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_observation-student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_observation-subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_observation-user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `role_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `role_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `school_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `role_type-school_id_idx` (`school_id` ASC),
  UNIQUE INDEX `role_unique` (`school_id` ASC, `name` ASC),
  CONSTRAINT `role_type-school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_type_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `role_type_id_idx` (`role_type_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  UNIQUE INDEX `role_unique` (`user_id` ASC, `role_type_id` ASC),
  CONSTRAINT `role-role_type_id`
    FOREIGN KEY (`role_type_id`)
    REFERENCES `role_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role-user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_grade` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` INT UNSIGNED NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `grade_id` INT UNSIGNED NOT NULL,
  `student_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `grade_id_idx` (`grade_id` ASC),
  INDEX `student_id_idx` (`student_id` ASC),
  CONSTRAINT `student_grade-grade_id`
    FOREIGN KEY (`grade_id`)
    REFERENCES `grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_grade-student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medical_report` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(50) NOT NULL,
  `student_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `student_id_idx` (`student_id` ASC),
  UNIQUE INDEX `medical_report_unique` (`student_id` ASC, `description` ASC),
  CONSTRAINT `medical_report-student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical_report_subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medical_report_subject` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `medical_report_id` INT UNSIGNED NOT NULL,
  `subject_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `medical_report_id_idx` (`medical_report_id` ASC),
  INDEX `subject_id_idx` (`subject_id` ASC),
  UNIQUE INDEX `medical_report_subject_unique` (`medical_report_id` ASC, `subject_id` ASC),
  CONSTRAINT `medical_report_subject-medical_report_id`
    FOREIGN KEY (`medical_report_id`)
    REFERENCES `medical_report` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `medical_report_subject-subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_token` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(255) NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC),
  UNIQUE INDEX `value_UNIQUE` (`value` ASC),
  CONSTRAINT `user_token-user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `council_topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `council_topic` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `council_id` INT UNSIGNED NOT NULL,
  `topic_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `council_topic-topic_id_idx` (`topic_id` ASC),
  INDEX `council_topic-council_id_idx` (`council_id` ASC),
  UNIQUE INDEX `council_topic_unique` (`council_id` ASC, `topic_id` ASC),
  CONSTRAINT `council_topic-topic_id`
    FOREIGN KEY (`topic_id`)
    REFERENCES `topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `council_topic-council_id`
    FOREIGN KEY (`council_id`)
    REFERENCES `council` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `permission` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `reference` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `reference_UNIQUE` (`reference` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `role_type_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `role_type_permission` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `permission_id` INT UNSIGNED NOT NULL,
  `role_type_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `role_type_permission_unique` (`role_type_id` ASC, `permission_id` ASC),
  INDEX `role_type_permission-role_type_id_idx` (`role_type_id` ASC),
  INDEX `role_type_permission-permission_id_idx` (`permission_id` ASC),
  CONSTRAINT `role_type_permission-role_type_id`
    FOREIGN KEY (`role_type_id`)
    REFERENCES `role_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_type_permission-permission_id`
    FOREIGN KEY (`permission_id`)
    REFERENCES `permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `role_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `role_request` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_type_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `role_request_unique` (`user_id` ASC, `role_type_id` ASC),
  INDEX `role_request-role_type_id_idx` (`role_type_id` ASC),
  CONSTRAINT `role_request-role_type_id`
    FOREIGN KEY (`role_type_id`)
    REFERENCES `role_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_request-user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teacher` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `grade_id` INT UNSIGNED NOT NULL,
  `subject_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `teacher-grade_id_idx` (`grade_id` ASC),
  INDEX `teacher-subject_id_idx` (`subject_id` ASC),
  INDEX `teacher-user_id_idx` (`user_id` ASC),
  CONSTRAINT `teacher-grade_id`
    FOREIGN KEY (`grade_id`)
    REFERENCES `grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `teacher-subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `teacher-user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teacher_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teacher_request` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `grade_id` INT UNSIGNED NOT NULL,
  `subject_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `teacher_request-grade_id_idx` (`grade_id` ASC),
  INDEX `teacher_request-subject_id_idx` (`subject_id` ASC),
  INDEX `teacher_request-user_id_idx` (`user_id` ASC),
  UNIQUE INDEX `teacher_request_unique` (`user_id` ASC, `subject_id` ASC, `grade_id` ASC),
  CONSTRAINT `teacher_request-grade_id`
    FOREIGN KEY (`grade_id`)
    REFERENCES `grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `teacher_request-subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `teacher_request-user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `council_grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `council_grade` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `council_id` INT UNSIGNED NOT NULL,
  `grade_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `council_grade-council_id_idx` (`council_id` ASC),
  INDEX `council_grade-grade_id_idx` (`grade_id` ASC),
  UNIQUE INDEX `council_grade_unique` (`grade_id` ASC, `council_id` ASC),
  CONSTRAINT `council_grade-council_id`
    FOREIGN KEY (`council_id`)
    REFERENCES `council` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `council_grade-grade_id`
    FOREIGN KEY (`grade_id`)
    REFERENCES `grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
